# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ban_words.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ban_words.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62\x61n_words.proto\x12\x08settings\"@\n\x17RetrieveBanWordsRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x03\x12\x12\n\nupdated_at\x18\x02 \x01(\t\"M\n\x08\x42\x61nWords\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05words\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\x12\x12\n\nupdated_at\x18\x04 \x01(\t2^\n\x0f\x42\x61nWordsService\x12K\n\x10RetrieveBanWords\x12!.settings.RetrieveBanWordsRequest\x1a\x12.settings.BanWords\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ban_words_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVEBANWORDSREQUEST']._serialized_start=29
  _globals['_RETRIEVEBANWORDSREQUEST']._serialized_end=93
  _globals['_BANWORDS']._serialized_start=95
  _globals['_BANWORDS']._serialized_end=172
  _globals['_BANWORDSSERVICE']._serialized_start=174
  _globals['_BANWORDSSERVICE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
