# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: campaigns.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'campaigns.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61mpaigns.proto\x12\x08\x63\x61mpaign\"\x90\x02\n\x08\x43\x61mpaign\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x15\n\rtarget_amount\x18\x04 \x01(\t\x12\x18\n\x10\x63ollected_amount\x18\x05 \x01(\t\x12\x1b\n\x13progress_percentage\x18\x06 \x01(\x02\x12\x11\n\tis_active\x18\x07 \x01(\x08\x12\x12\n\nis_default\x18\x08 \x01(\x08\x12\x12\n\ncreated_at\x18\t \x01(\t\x12\x12\n\nupdated_at\x18\n \x01(\t\x12\x10\n\x08start_at\x18\x0b \x01(\t\x12\x0e\n\x06\x65nd_at\x18\x0c \x01(\t\x12\x15\n\ris_active_now\x18\r \x01(\x08\"5\n\x0c\x43\x61mpaignList\x12%\n\tcampaigns\x18\x01 \x03(\x0b\x32\x12.campaign.Campaign\")\n\x14GetByAuthorIDRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x03\"@\n\x16GetByIDAuthorIDRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x03\x12\x13\n\x0b\x63\x61mpaign_id\x18\x02 \x01(\x03\x32\xa8\x01\n\x0f\x43\x61mpaignService\x12I\n\x0fGetByIDAuthorID\x12 .campaign.GetByIDAuthorIDRequest\x1a\x12.campaign.Campaign\"\x00\x12J\n\x0eListByAuthorID\x12\x1e.campaign.GetByAuthorIDRequest\x1a\x16.campaign.CampaignList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'campaigns_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMPAIGN']._serialized_start=30
  _globals['_CAMPAIGN']._serialized_end=302
  _globals['_CAMPAIGNLIST']._serialized_start=304
  _globals['_CAMPAIGNLIST']._serialized_end=357
  _globals['_GETBYAUTHORIDREQUEST']._serialized_start=359
  _globals['_GETBYAUTHORIDREQUEST']._serialized_end=400
  _globals['_GETBYIDAUTHORIDREQUEST']._serialized_start=402
  _globals['_GETBYIDAUTHORIDREQUEST']._serialized_end=466
  _globals['_CAMPAIGNSERVICE']._serialized_start=469
  _globals['_CAMPAIGNSERVICE']._serialized_end=637
# @@protoc_insertion_point(module_scope)
