# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

import protobuf.donations_pb2 as donations__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in donations_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DonationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnionByDonorNamesList = channel.unary_unary(
            "/donations.DonationService/UnionByDonorNamesList",
            request_serializer=donations__pb2.UnionByDonorNamesListRequest.SerializeToString,
            response_deserializer=donations__pb2.UnionByDonorNamesDonationsListResponse.FromString,
            _registered_method=True,
        )
        self.LastDonationsList = channel.unary_unary(
            "/donations.DonationService/LastDonationsList",
            request_serializer=donations__pb2.LastDonationsListRequest.SerializeToString,
            response_deserializer=donations__pb2.LastDonationsListResponse.FromString,
            _registered_method=True,
        )


class DonationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UnionByDonorNamesList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LastDonationsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DonationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "UnionByDonorNamesList": grpc.unary_unary_rpc_method_handler(
            servicer.UnionByDonorNamesList,
            request_deserializer=donations__pb2.UnionByDonorNamesListRequest.FromString,
            response_serializer=donations__pb2.UnionByDonorNamesDonationsListResponse.SerializeToString,
        ),
        "LastDonationsList": grpc.unary_unary_rpc_method_handler(
            servicer.LastDonationsList,
            request_deserializer=donations__pb2.LastDonationsListRequest.FromString,
            response_serializer=donations__pb2.LastDonationsListResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("donations.DonationService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("donations.DonationService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class DonationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UnionByDonorNamesList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/donations.DonationService/UnionByDonorNamesList",
            donations__pb2.UnionByDonorNamesListRequest.SerializeToString,
            donations__pb2.UnionByDonorNamesDonationsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LastDonationsList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/donations.DonationService/LastDonationsList",
            donations__pb2.LastDonationsListRequest.SerializeToString,
            donations__pb2.LastDonationsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
