# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protobuf.donators_videos_pb2 as donators__videos__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in donators_videos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DonatorsVideosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDonatorsVideos = channel.unary_unary(
                '/donations.DonatorsVideosService/ListDonatorsVideos',
                request_serializer=donators__videos__pb2.ListDonatorsVideosRequest.SerializeToString,
                response_deserializer=donators__videos__pb2.ListDonatorsVideosResponse.FromString,
                _registered_method=True)


class DonatorsVideosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDonatorsVideos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DonatorsVideosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDonatorsVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDonatorsVideos,
                    request_deserializer=donators__videos__pb2.ListDonatorsVideosRequest.FromString,
                    response_serializer=donators__videos__pb2.ListDonatorsVideosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'donations.DonatorsVideosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('donations.DonatorsVideosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DonatorsVideosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDonatorsVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donations.DonatorsVideosService/ListDonatorsVideos',
            donators__videos__pb2.ListDonatorsVideosRequest.SerializeToString,
            donators__videos__pb2.ListDonatorsVideosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
