# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: donators_videos.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'donators_videos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64onators_videos.proto\x12\tdonations\"B\n\x19ListDonatorsVideosRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x03\x12\x12\n\nupdated_at\x18\x02 \x01(\t\"E\n\x1aListDonatorsVideosResponse\x12\'\n\x06videos\x18\x01 \x03(\x0b\x32\x17.donations.DonatorVideo\";\n\x0c\x44onatorVideo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t2|\n\x15\x44onatorsVideosService\x12\x63\n\x12ListDonatorsVideos\x12$.donations.ListDonatorsVideosRequest\x1a%.donations.ListDonatorsVideosResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'donators_videos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTDONATORSVIDEOSREQUEST']._serialized_start=36
  _globals['_LISTDONATORSVIDEOSREQUEST']._serialized_end=102
  _globals['_LISTDONATORSVIDEOSRESPONSE']._serialized_start=104
  _globals['_LISTDONATORSVIDEOSRESPONSE']._serialized_end=173
  _globals['_DONATORVIDEO']._serialized_start=175
  _globals['_DONATORVIDEO']._serialized_end=234
  _globals['_DONATORSVIDEOSSERVICE']._serialized_start=236
  _globals['_DONATORSVIDEOSSERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
