# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: groups.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'groups.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf.settings_pb2 as settings__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgroups.proto\x12\x06groups\x1a\x0esettings.proto\"\x81\x01\n\x12\x41lertSettingsGroup\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\nupdated_at\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\x03\x12.\n\x0e\x61lert_settings\x18\x05 \x03(\x0b\x32\x16.settings.AlertSetting\"\\\n!AlertSettingsGroupRetrieveRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x03\x12\x10\n\x08group_id\x18\x02 \x01(\x03\x12\x12\n\nupdated_at\x18\x03 \x01(\t2s\n\x1c\x41lertSettingsGroupController\x12S\n\x08Retrieve\x12).groups.AlertSettingsGroupRetrieveRequest\x1a\x1a.groups.AlertSettingsGroup\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groups_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALERTSETTINGSGROUP']._serialized_start=41
  _globals['_ALERTSETTINGSGROUP']._serialized_end=170
  _globals['_ALERTSETTINGSGROUPRETRIEVEREQUEST']._serialized_start=172
  _globals['_ALERTSETTINGSGROUPRETRIEVEREQUEST']._serialized_end=264
  _globals['_ALERTSETTINGSGROUPCONTROLLER']._serialized_start=266
  _globals['_ALERTSETTINGSGROUPCONTROLLER']._serialized_end=381
# @@protoc_insertion_point(module_scope)
