# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moderation_settings.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "moderation_settings.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19moderation_settings.proto\x12\x08settings"I\n RetrieveModerationSettingRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x03\x12\x12\n\nupdated_at\x18\x02 \x01(\t"\x87\x01\n\x11ModerationSetting\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tis_active\x18\x02 \x01(\x08\x12\x10\n\x08\x64uration\x18\x03 \x01(\x05\x12\x19\n\x11\x61\x63tivation_amount\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t2\x83\x01\n\x19ModerationSettingsService\x12\x66\n\x19RetrieveModerationSetting\x12*.settings.RetrieveModerationSettingRequest\x1a\x1b.settings.ModerationSetting"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "moderation_settings_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_RETRIEVEMODERATIONSETTINGREQUEST"]._serialized_start = 39
    _globals["_RETRIEVEMODERATIONSETTINGREQUEST"]._serialized_end = 112
    _globals["_MODERATIONSETTING"]._serialized_start = 115
    _globals["_MODERATIONSETTING"]._serialized_end = 250
    _globals["_MODERATIONSETTINGSSERVICE"]._serialized_start = 253
    _globals["_MODERATIONSETTINGSSERVICE"]._serialized_end = 384
# @@protoc_insertion_point(module_scope)
