# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: top_donaters.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'top_donaters.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12top_donaters.proto\x12\x08settings\"O\n&RetrieveStatisticWidgetSettingsRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x03\x12\x12\n\nsetting_id\x18\x02 \x01(\x03\"\xba\x03\n\x17StatisticWidgetSettings\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04user\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0e\n\x06period\x18\x05 \x01(\t\x12\x16\n\x0e\x65lements_count\x18\x06 \x01(\x05\x12\x11\n\tview_type\x18\x07 \x01(\t\x12\x17\n\x0fstring_template\x18\x08 \x01(\t\x12\x12\n\ncreated_at\x18\t \x01(\t\x12\x12\n\nupdated_at\x18\n \x01(\t\x12\x0c\n\x04\x66ont\x18\x0b \x01(\t\x12\r\n\x05\x63olor\x18\x0c \x01(\t\x12\r\n\x05style\x18\r \x01(\t\x12\x12\n\nfont_align\x18\x0e \x01(\t\x12\x11\n\tfont_size\x18\x0f \x01(\x05\x12\x14\n\x0cshadow_color\x18\x10 \x01(\t\x12 \n\x18shadow_horizontal_offset\x18\x11 \x01(\x05\x12\x1e\n\x16shadow_vertical_offset\x18\x12 \x01(\x05\x12\x13\n\x0bshadow_blur\x18\x13 \x01(\x05\x12\x15\n\rcontour_color\x18\x14 \x01(\t\x12\x15\n\rcontour_width\x18\x15 \x01(\x05\x32\x9a\x01\n\x1eStatisticWidgetSettingsService\x12x\n\x1fRetrieveStatisticWidgetSettings\x12\x30.settings.RetrieveStatisticWidgetSettingsRequest\x1a!.settings.StatisticWidgetSettings\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'top_donaters_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVESTATISTICWIDGETSETTINGSREQUEST']._serialized_start=32
  _globals['_RETRIEVESTATISTICWIDGETSETTINGSREQUEST']._serialized_end=111
  _globals['_STATISTICWIDGETSETTINGS']._serialized_start=114
  _globals['_STATISTICWIDGETSETTINGS']._serialized_end=556
  _globals['_STATISTICWIDGETSETTINGSSERVICE']._serialized_start=559
  _globals['_STATISTICWIDGETSETTINGSSERVICE']._serialized_end=713
# @@protoc_insertion_point(module_scope)
