# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protobuf.top_donaters_pb2 as top__donaters__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in top_donaters_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TopDonatersSettingsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RetrieveTopDonatersSetting = channel.unary_unary(
                '/settings.TopDonatersSettingsService/RetrieveTopDonatersSetting',
                request_serializer=top__donaters__pb2.RetrieveTopDonatersSettingRequest.SerializeToString,
                response_deserializer=top__donaters__pb2.TopDonatersSetting.FromString,
                _registered_method=True)


class TopDonatersSettingsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RetrieveTopDonatersSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopDonatersSettingsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrieveTopDonatersSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveTopDonatersSetting,
                    request_deserializer=top__donaters__pb2.RetrieveTopDonatersSettingRequest.FromString,
                    response_serializer=top__donaters__pb2.TopDonatersSetting.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'settings.TopDonatersSettingsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('settings.TopDonatersSettingsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TopDonatersSettingsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RetrieveTopDonatersSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settings.TopDonatersSettingsService/RetrieveTopDonatersSetting',
            top__donaters__pb2.RetrieveTopDonatersSettingRequest.SerializeToString,
            top__donaters__pb2.TopDonatersSetting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
