# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protobuf.widget_videos_pb2 as widget__videos__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in widget_videos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListWidgetVideos = channel.unary_unary(
                '/settings.VideosService/ListWidgetVideos',
                request_serializer=widget__videos__pb2.ListWidgetVideosRequest.SerializeToString,
                response_deserializer=widget__videos__pb2.ListWidgetVideosResponse.FromString,
                _registered_method=True)


class VideosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListWidgetVideos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListWidgetVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWidgetVideos,
                    request_deserializer=widget__videos__pb2.ListWidgetVideosRequest.FromString,
                    response_serializer=widget__videos__pb2.ListWidgetVideosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'settings.VideosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('settings.VideosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListWidgetVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settings.VideosService/ListWidgetVideos',
            widget__videos__pb2.ListWidgetVideosRequest.SerializeToString,
            widget__videos__pb2.ListWidgetVideosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
