# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget_video_settings.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'widget_video_settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bwidget_video_settings.proto\x12\x08settings\"K\n\"RetrieveWidgetVideoSettingsRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x03\x12\x12\n\nupdated_at\x18\x02 \x01(\t\"\xd8\x01\n\x13WidgetVideoSettings\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rplay_randomly\x18\x02 \x01(\x08\x12\x12\n\nshow_video\x18\x03 \x01(\x08\x12\x0e\n\x06volume\x18\x04 \x01(\x05\x12\x15\n\rborder_radius\x18\x05 \x01(\x05\x12 \n\x18when_to_show_video_title\x18\x06 \x01(\t\x12\x41\n\x18last_viewed_widget_video\x18\x07 \x01(\x0b\x32\x1f.settings.LastViewedWidgetVideo\";\n\x15LastViewedWidgetVideo\x12\x15\n\x08video_id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x42\x0b\n\t_video_id2\x8a\x01\n\x1aWidgetVideoSettingsService\x12l\n\x1bRetrieveWidgetVideoSettings\x12,.settings.RetrieveWidgetVideoSettingsRequest\x1a\x1d.settings.WidgetVideoSettings\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget_video_settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVEWIDGETVIDEOSETTINGSREQUEST']._serialized_start=41
  _globals['_RETRIEVEWIDGETVIDEOSETTINGSREQUEST']._serialized_end=116
  _globals['_WIDGETVIDEOSETTINGS']._serialized_start=119
  _globals['_WIDGETVIDEOSETTINGS']._serialized_end=335
  _globals['_LASTVIEWEDWIDGETVIDEO']._serialized_start=337
  _globals['_LASTVIEWEDWIDGETVIDEO']._serialized_end=396
  _globals['_WIDGETVIDEOSETTINGSSERVICE']._serialized_start=399
  _globals['_WIDGETVIDEOSETTINGSSERVICE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
