# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget_videos.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'widget_videos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13widget_videos.proto\x12\x08settings\"@\n\x17ListWidgetVideosRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x03\x12\x12\n\nupdated_at\x18\x02 \x01(\t\"A\n\x18ListWidgetVideosResponse\x12%\n\x06videos\x18\x01 \x03(\x0b\x32\x15.settings.WidgetVideo\":\n\x0bWidgetVideo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t2l\n\rVideosService\x12[\n\x10ListWidgetVideos\x12!.settings.ListWidgetVideosRequest\x1a\".settings.ListWidgetVideosResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget_videos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTWIDGETVIDEOSREQUEST']._serialized_start=33
  _globals['_LISTWIDGETVIDEOSREQUEST']._serialized_end=97
  _globals['_LISTWIDGETVIDEOSRESPONSE']._serialized_start=99
  _globals['_LISTWIDGETVIDEOSRESPONSE']._serialized_end=164
  _globals['_WIDGETVIDEO']._serialized_start=166
  _globals['_WIDGETVIDEO']._serialized_end=224
  _globals['_VIDEOSSERVICE']._serialized_start=226
  _globals['_VIDEOSSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
